import type { Metadata } from "next";
import localFont from "next/font/local";
import "../styles/globals.css";

const CommitLight = localFont({
  src: "./fonts/CommitMono-400-Regular.otf",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const CommitBold = localFont({
  src: "./fonts/CommitMono-700-Regular.otf",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${CommitBold.variable} ${CommitLight.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
